# This is the env setup for installing and running ISCE and FRINGE.

# create environment : mamba env create -f requirements.yml
# update dependencies: mamba env update -f requirements.yml
# remove environment : mamba env remove -n isce
# enter  environment : conda activate isce
# exit   environment : conda deactivate
name: isce
channels:
  - conda-forge
  - defaults
dependencies:
  - python==3.10.0
# For ISCE-2
#  - isce2
  - git
  - cmake
  - cython
  - gdal
  - h5py
  - libgdal
  - pytest
  - numpy
  - fftw
  - scipy
  - pybind11
  - shapely
# For MDX
  - openmotif
  - openmotif-dev
  - xorg-libx11
  - xorg-libxt
  - xorg-libxmu
  - xorg-libxft
  - libiconv
  - xorg-libxrender
  - xorg-libxau
  - xorg-libxdmcp
# For compiling isce (if you don't have access to system installed compiler [recommended])
#  - gcc_linux-64
#  - gxx_linux-64
#  - gfortran_linux-64

# Other
  - mintpy
  - lxml
  - scikit-image
  - matplotlib
  - cartopy
  - astropy
  - pandas
  - lxml
  - opencv
  - spyder
  - "libblas=*=*mkl"
  - mkl

# For Dolphin
  - isce3
  - hdf5!=1.12.2 # https://github.com/SciTools/iris/issues/5187 and https://github.com/pydata/xarray/issues/7549
  - numba>=0.54
  - opera-utils>=0.1.5
  - pydantic>=2.1
  - pymp-pypi>=0.4.5
  - pyproj>=3.3
  - rasterio>=1.3
  - rich>=12.0
  - ruamel.yaml>=0.15
  - tbb>=2021.6.0 # Module for numba threading which prevents `fork()` crashes
  - threadpoolctl>=3.0
  - typing_extensions>=3.10
# For Dolphin GPU version
#  - cupy>=11.0
  - cudatoolkit
  - pynvml>=11.0
